document.write("<script language='javascript' src='config.js'></script>");document.write("<script language='javascript' src='utility.js'></script>");document.write("<script language='javascript' src='player.js'></script>");document.write("<script language='javascript' src='global.js'></script>")
function GameStart(context,contxtScore){InitGame(context,contxtScore);RunGame(context,contxtScore)}
function InitGame(context,contxtScore){for(var i=initSize;i>0;i--){snakeArr[i-1]=new Object();snakeArr[i-1].x=(initSize-i+1)*unitSize;snakeArr[i-1].y=0};direction="right";food=new Object();DrawScreen(context);RandomFood(context);DrawScore(contxtScore,score)}
function RunGame(context,contxtScore){if(timer)clearInterval(timer);timer=setInterval(function(){if(IsGameOver()){alert("game over!");clearInterval(timer);return};EatFoodHandler(context,contxtScore);Refresh(context);SetPosition();DrawSnake(context)},sleepTime)}
function Refresh(context){FillRect(context,snakeArr[snakeArr.length-1].x,snakeArr[snakeArr.length-1].y,unitSize,unitSize,screenColor);DrawRect(context,snakeArr[snakeArr.length-1].x,snakeArr[snakeArr.length-1].y,unitSize,unitSize,lineColor)}
function DrawSnake(context){for(var i=0;i<snakeArr.length;i++){FillRect(context,snakeArr[i].x,snakeArr[i].y,unitSize,unitSize,snakeColor);DrawRect(context,snakeArr[i].x,snakeArr[i].y,unitSize,unitSize,lineColor)}}
function DrawScreen(context){for(var i=screenLeft;i<screenLeft+screenWidth/unitSize;i++)for(var j=screenTop;j<screenTop+screenHeight/unitSize;j++){FillRect(context,i*unitSize,j*unitSize,unitSize,unitSize,screenColor);DrawRect(context,i*unitSize,j*unitSize,unitSize,unitSize,lineColor)}}
function SetPosition(){for(var i=snakeArr.length-2;i>=0;i--){snakeArr[i+1].x=snakeArr[i].x;snakeArr[i+1].y=snakeArr[i].y};if(direction=="left"){snakeArr[0].x-=unitSize}else if(direction=="right"){snakeArr[0].x+=unitSize}else if(direction=="up"){snakeArr[0].y-=unitSize}else if(direction=="down")snakeArr[0].y+=unitSize}
function IsGameOver(){if(snakeArr[0].x<0||snakeArr[0].x>screenWidth)return true;if(snakeArr[0].y<0||snakeArr[0].y>screenHeight)return true;for(var i=1;i<snakeArr.length;i++)if(snakeArr[0].x==snakeArr[i].x&&snakeArr[0].y==snakeArr[i].y){gameStatus=3;return true};return false}
function RandomFood(context){food.x=GetRandom((screenWidth/unitSize)-1)*unitSize;food.y=GetRandom((screenHeight/unitSize)-1)*unitSize;for(var i=0;i<snakeArr.length;i++)if(food.x==snakeArr[i].x&&food.y==snakeArr[i].y)RandomFood(context);FillRect(context,food.x,food.y,unitSize,unitSize,foodColor);DrawRect(context,food.x,food.y,unitSize,unitSize,lineColor)}
function EatFoodHandler(context,contxtScore){if(direction=="left"){if((snakeArr[0].x-unitSize==food.x)&&snakeArr[0].y==food.y){IncreaseLen(contxtScore);ClearFood(context);RandomFood(context)}}else if(direction=="right"){if(snakeArr[0].x+unitSize==food.x&&snakeArr[0].y==food.y){IncreaseLen(contxtScore);ClearFood(context);RandomFood(context)}}else if(direction=="up"){if(snakeArr[0].x==food.x&&(snakeArr[0].y-unitSize==food.y)){IncreaseLen(contxtScore);ClearFood(context);RandomFood(context)}}else if(direction=="down")if(snakeArr[0].x==food.x&&snakeArr[0].y+unitSize==food.y){IncreaseLen(contxtScore);ClearFood(context);RandomFood(context)}}
function ClearFood(context){FillRect(context,food.x,food.y,unitSize,unitSize,screenColor);DrawRect(context,food.x,food.y,unitSize,unitSize,lineColor)}
function IncreaseLen(contxtScore){var newObj=new Object();newObj.x=food.x;newObj.y=food.y;snakeArr.unshift(newObj);IncreaseScore(contxtScore)}
function PauseGame(){clearInterval(timer)}